name: Build and test

on: [push, pull_request]

env:
  testDir: ${{ github.workspace }}/test/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-2019
          - os: macos-10.15

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
            python-version: "3.x"

      - uses: lukka/get-cmake@latest

      - name: Test script
        run: cd "${{ env.testDir }}"; mkdir build; cd build; cmake ..
        shell: bash
